# Generated by Django 3.0.5 on 2021-05-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WorksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('city', models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, related_name='person_street', to='question2_app.LivesModel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question2_app.WorksModel')),
                ('street', models.ForeignKey(max_length=300, on_delete=django.db.models.deletion.CASCADE, related_name='preson_city', to='question2_app.LivesModel')),
            ],
        ),
    ]
