# Generated by Django 3.0.5 on 2021-06-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('regno', models.IntegerField()),
                ('cgpa', models.FloatField()),
            ],
        ),
    ]
