# Generated by Django 3.0.5 on 2021-05-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question2_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olaridemodel',
            name='eta',
        ),
    ]
